### ISSUE TITLE
conda create env has no force parameter

### ISSUE THREAD

**Issue by ahmadia** [conda/conda-env#101]
Sometimes I don't want to update my environment, I just want to make sure the environment is what I say it is.  That means I need to be able to run `conda create env --force`, which should remove any existing environments and run the create.  See https://github.com/memex-explorer/memex-explorer/pull/580#issuecomment-112255568

**Comment by malev** [comment]
@ahmadia there is a PR about this https://github.com/conda/conda-env/pull/102

**Comment by malev** [comment]
we do have:
`conda env create --force`
Is that ok?

**Comment by ahmadia** [comment]
Perfect, thanks.
