### ISSUE TITLE
Add conda env path command

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda-env#109]
To determine the conda env path in a bash script I do this:
```      
 env_path=`conda env list | grep -e "^${conda_env_name} " | awk '{print $(NF)}'`
```

A conda env path command would be great to have instead
```
      env_path=`conda env path -n ${conda_env_name}`
```

**Comment by malev** [comment]
Some people asked for something similar to this, they want to be able to list only names:
```sh
$ conda env list --only-names
stats
py27
root
```
I guess we could easily have `--only-prefix` as well:
```sh
$ conda env list --only-prefix
/Users/mvanetta/miniconda3/envs/stats
/Users/mvanetta/miniconda3/envs/py27
/Users/mvanetta/miniconda3
```
And more specific:
```sh
$ conda env list --only-prefix stats
/Users/mvanetta/miniconda3/envs/stats
```

My question is, where would this be useful?

**Comment by bkreider** [comment]
Wait, is this for the current $PREFIX or for any named env path?  I think most needs are for the current path.  This was implemented in conda-env as an environment variable.  https://github.com/conda/conda-env/issues/63.  CONDA_ENV_PATH.  I've never used it but that looks like what you are looking for.

**Comment by malev** [comment]
Not sure what to do here so I'm closing

**Comment by joelhullcio** [comment]
@malev looks like I missed your question above.
This functionality is helpful when writing scripts that manage envs, deploy packages and/or work with conda in general.  Often times in a script the name of env only is known but in order to update perform various operations on it the full path to the env is needed.  Since envs prefixes can exist anywhere on the system it would be best to get the prefix from conda.  A clean interface is needed for this.

Bash script example that would be helpful.  Just returns the full path (prefix) to the env.
    
    env_path=`conda env path -n ${conda_env_name}`

**Comment by malev** [comment]
@joelhullcio thanks! will work on this

**Comment by joelhullcio** [comment]
@malev thank you.  Also, if the env doesn't exist, return an empty string and exit with a successful status (0).  Do not output an error message or exit with an error status if the env doesn't exist.  An error message or exit status complicates using this feature in scripts.

**Comment by malev** [comment]
@joelhullcio when you have an environment activated you have access to the env variable `CONDA_ENV_PATH`:
This should be enough. Don't you think?
