### ISSUE TITLE
%LIBRARY_BIN% not added to %PATH% when activating an environment in Windows

### ISSUE THREAD

**Issue by campos-ddc** [conda/conda-env#115]
From what I can see, activating an environment in Windows will add the following directories to `%PATH%`:

* `%PREFIX%`
* `%PREFIX%/Script` (or `%SCRIPTS%` during the build process)

But `%PREFIX%/Library/bin` (or `%LIBRARY_BIN%` during the build process) is *not* added.

Is this intentional?

**Comment by malev** [comment]
In what situation would you need that? As far as I know, when you run `conda-build` the build process happens in a complete isolated environment, independent from the environment that you are using.

**Comment by campos-ddc** [comment]
This is not related to conda-build, I just think that this path should be set because all unix-like packages will put their executables in Library/bin when installed in Windows.

We need this for our git and vtk packages, there may be more, but I don't remember them right now.

**Comment by malev** [comment]
I'm not aware of that situation. Maybe you should use post-activate scripts in order to achieve this custom solution

**Comment by groutr** [comment]
I agree.  I think it would be nice to have %LIBRARY_BIN% in the path.  A lot of packages put binaries and other utilities in this bin directory.

**Comment by msarahan** [comment]
We will do this.  Re-opening this so it doesn't get lost.

**Comment by malev** [comment]
@msarahan what about https://github.com/conda/conda-env/blob/develop/bin/activate.bat#L59 ?

**Comment by msarahan** [comment]
Yes, this should fix things for the most part.  There's still some potential for things to be different during package building.  I guess I just want to keep this open until I have tested it all and know that it is completely working.

**Comment by msarahan** [comment]
Between conda-env and https://github.com/conda/conda-build/pull/601 this should be fixed.  However, existing root environments will not have Library/bin on PATH.  Users will need to manually add that, if they are depending on things being set up from the installer setting PATH for them.

**Comment by marscher** [comment]
It is nice that the PATH is being when using the installer but what about existing installations? The average user is not able to set env variables and therefore can not use his/her software any more.
