### ISSUE TITLE
Pick particular build when declaring dependencies

### ISSUE THREAD

**Issue by campos-ddc** [conda/conda-env#123]
There is a good chance that I'm missing something, but I think I'm not able to pick a particular build when declaring dependencies in environment.yml

I would assume that the syntax would be similar to `conda create`, something like this:

```yaml
dependencies:
  - dont_care
  - need_version==1.5.7
  - need_version_and_build==1.5.7=2
```

**Comment by malev** [comment]
@campos-dcc the syntax is:

```
name: root
dependencies:
- binstar=0.11.0=py34_0
- binstar-build=0.10.7=py34_0
- certifi=14.05.14=py34_0
- clyent=0.3.4=py34_0
```

**Comment by malev** [comment]
if that answer your question, please close this issue. tnx
