### ISSUE TITLE
`conda.install.rm_rf` can't delete old environments in Windows + Python 2.7

### ISSUE THREAD

**Issue by campos-ddc** [conda/conda-env#124]
This issue hit me when trying to use `--force` option in `conda env create` (I added this in #102), and it revealed a possible problem with how conda handles links in Windows + Python 2.7.

# Symptom

Trying to delete an environment (not active) from within Python fails because the original file being linked is locked by Windows.

# Context

* Windows
* Python 2.7 (`os.islink` does not work here, which might affect the `rm_rf` function from `conda.install`)

# Reproducing

This command line is enough to reproduce the problem:

```bat
$ conda create -n test pyyaml && python -c "import yaml;from conda.install import rm_rf;rm_rf('C:\\Miniconda\\envs\\test')"
Fetching package metadata: ......

#
# To activate this environment, use:
# > activate test
#

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 204, in rm_rf
    shutil.rmtree(path)
  File "C:\Miniconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Miniconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Miniconda\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Miniconda\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Acesso negado: 'C:\\Miniconda\\envs\\test\\Lib\\site-packages\\yaml.dll'
```

Note that when I import `pyyaml`, I'm locking file `C:\\Miniconda\\Lib\\site-packages\\yaml.dll` (root environment), but that also prevents me from deleting `C:\\Miniconda\\envs\\test\\Lib\\site-packages\\yaml.dll` (another hard link).

# Solution?

Maybe we should add some improved support for detecting and unlinking hardlinks in Windows with Python 2.7, and handle those cases individually instead of trying to `shutil.rmtree` everything.

Possibly from [jarako.windows](https://bitbucket.org/jaraco/jaraco.windows/src/default/jaraco/windows/filesystem/__init__.py#cl-76) or [ntfs/fs.py](https://github.com/sid0/ntfs/blob/master/ntfsutils/fs.py#L88)

**Comment by campos-ddc** [comment]
Not sure if I should post this in `conda` or `conda-env`, since the problem seems to lie in `rm_rf`, but its `conda_env` calling it.

**Comment by malev** [comment]
@campos-ddc in the example you are using `conda` at first glance looks like this problem belongs to `conda`. Thanks for reporting!

**Comment by campos-ddc** [comment]
Should I move it there?

**Comment by malev** [comment]
yes please. Closing here
