### ISSUE TITLE
conda update needs a way to update from a remote env definition

### ISSUE THREAD

**Issue by ijstokes** [conda/conda-env#136]
I created a conda env by using `conda env create ijstokes/weather_py34` to fetch an env definition from http://anaconda.org/ijstokes/foo.  A few days later `ijstokes/weather_py34` has been updated on the server, and now I want to update my local env to match.  I'd like to do `conda env update ijstokes/weather_py34`.  This seems reasonable, but doesn't appear to be possible.

**Comment by malev** [comment]
Great idea!
