### ISSUE TITLE
"conda env list --json" output environment names

### ISSUE THREAD

**Issue by alanhdu** [conda/conda-env#147]
It'd be nice if `conda env list --json` returned the environment names, along with their paths.

Maybe something like:
```bash
$ conda env list --json
{
  "envs": {
    "test": "/home/alan/miniconda3/envs/test",
    "website": "/home/alan/miniconda3/envs/website"
  }
}
```
instead of 
```bash
$ conda env list --json
{
  "envs": [
    "/home/alan/miniconda3/envs/test",
    "/home/alan/miniconda3/envs/website"
  ]
}
```

**Comment by malev** [comment]
sounds good, but what would be the usage of that? (thanks for reporting)

**Comment by alanhdu** [comment]
My particular use case was provisioning some VMs with conda (I wanted to check whether certain environments were already created to avoid overwriting existing environments). Eventually, I just checked for the existence of `/opt/conda/env/<name>`, but it'd be nice to check the name exactly.

OTOH, you can have multiple environments w/ the same name, so maybe I should just be checking for the path existence...

```bash
$ conda info -e
# conda environments:
#
my-root                  /home/vagrant/.conda/envs/my-root
name                     /home/vagrant/.conda/envs/name
blah                     /opt/conda/envs/blah
name                     /opt/conda/envs/name
root                  *  /opt/conda
```

**Comment by malev** [comment]
@alanhdu it sounds like a very specific use case. To be honest, don't think I'll prioritize this for now. You are welcome to submit a PR
