### ISSUE TITLE
environment.yml pip and git

### ISSUE THREAD

**Issue by steckerhalter** [conda/conda-env#149]
With pip it's possible to use something like: `pip install git+https://github.com/Kozea/WeasyPrint@master`

I tried this in `environment.yml` but it caused an error:

```
...
dependencies:
  - pip:
    - git+https://github.com/Kozea/WeasyPrint@master
```

Is this possible somehow?

**Comment by dusans** [comment]
I use git like this and it works. Notice the #egg=...

```
dependencies:
  - pip:
    - git+https://github.com/pyinstaller/pyinstaller.git#egg=pyinstaller
```

**Comment by dusans** [comment]
Also as a side note. If you create an issue and say there is an error... you should copy paste the error message.
We can only guess what your error could be.

**Comment by steckerhalter** [comment]
the "error" was: `# TODO handle more gracefully` that's why I didn't paste it...

I still get the same "error". Notice that above I'm trying to specify the branch (master). But trying to run the above example I also get `# TODO handle more gracefully`

Maybe I have to update conda-env? It seem to be integrated into conda now. Do I need to upgrade conda itself or is this not the same conda-env?

**Comment by steckerhalter** [comment]
I removed the env now and recreated it. Now it worked with the egg added. Quack!

Thanks for your help

**Comment by malev** [comment]
@steckerhalter so far conda-env does not support that kind of installations

**Comment by steckerhalter** [comment]
@malev Thanks, I think it worked ok after I had removed the env, but in the meantime WeasyPrint has released a new version with all the fixes included so I can use the normal method again

**Comment by mayerwin** [comment]
How can we include the equivalent of `pip install --upgrade https://github.com/dignio/ultrajson/tarball/master
`?
