### ISSUE TITLE
Environments support channel

### ISSUE THREAD

**Issue by malev** [conda/conda-env#155]
``` yaml
name: stats
dependencies:
  - malev:numpy
```
Can be parsed as: `numpy` from channel `malev`

**Comment by ahmadia** [comment]
+1

**Comment by malev** [comment]
As much as I'd love to have this feature working, first we would need some changes into conda

**Comment by ahmadia** [comment]
Agreed, let's chat about this when I'm in Austin.

**Comment by malev** [comment]
Since conda does not support this kind of installation I'm gonna close this
