### ISSUE TITLE
CONDA_ENVS_PATH is ignored by activate.bat on Windows

### ISSUE THREAD

**Issue by mikecroucher** [conda/conda-env#163]
The environment variable CONDA_ENVS_PATH is documented at  http://conda.pydata.org/docs/install/central.html

The documentation suggests doing something like
``set CONDA_ENVS_PATH=C:\Users\joe\envs;C:\Anaconda\envs``

The ``conda create`` command respects this variable -- new environments will be installed to ``C:\Users\joe\envs``. 

Unfortunately, the ``activate.bat`` script doesn't check this environment variable which leads to your newly created environment not being found.

**Comment by malev** [comment]
@mikecroucher, @msarahan has made significan changes in the `activate.bat` file. Maybe it will be fix with his patches. We will release a new version of `conda-env` soon, please let me know

**Comment by msarahan** [comment]
Current fixes don't address this, I don't think.  I will get a fix in soon, but I don't want this to hold up a release right now.

**Comment by msarahan** [comment]
Fixed by #164

**Comment by msarahan** [comment]
@mikecroucher thanks for this.  I have integrated your work with other stuff, and it all seems to play nicely.
