### ISSUE TITLE
Programmatic way to get the name of a created environment

### ISSUE THREAD

**Issue by ahmadia** [conda/conda-env#166]
I'm in a situation where I need to know what the environment in an environment.yml is named.  Is there a way to do this now in conda-env?  If not, can we add it?

**Comment by ahmadia** [comment]
Using: `sed -n 's/name:[[:space:]]*//p' environment.yml` as a workaround, but it ain't pretty.

**Comment by malev** [comment]
Looks like a feature requests. Not sure when I'll be able to work on this. Feel free to submit a PR.
