### ISSUE TITLE
activate.bat on Windows should check conda environment directories

### ISSUE THREAD

**Issue by remram44** [conda/conda-env#173]
Now that #60 is merged, conda can activate an environment by its full path on Windows. However @wulmer mentioned that relative paths and named environments living in one of the envs_dirs (listed in .condarc) is not possible; it should be addressed at some point.

I have no plan to do this myself currently, so anyone can jump in.

**Comment by yoavram** [comment]
I used your `activate.bat` (by downloading it and running it) for a relative path and it worked fine.

**Comment by malev** [comment]
@msarahan would you mind taking a look at this?

**Comment by msarahan** [comment]
Same as #163 I think.  I will work on this very soon, but probably not for this release.

**Comment by msarahan** [comment]
Fixed by #164
