### ISSUE TITLE
Pypi tarball doesn't contain activate.bat

### ISSUE THREAD

**Issue by jolos** [conda/conda-env#180]
Installing conda-env on windows using pip fails because the tarball ( https://pypi.python.org/pypi/conda-env/2.4.2 ) doesn't contain activate.bat. 

A workaround is to install it using:

pip install git+git://github.com/conda/conda-env.git@v2.4.2#egg=conda-env

**Comment by malev** [comment]
Thanks for reporting @jolos. Will work on this soon

**Comment by malev** [comment]
@jolos we are not maintaining the `pypi` package anymore. The best way to install `conda-env` is to run: `conda install conda-env`

**Comment by jolos** [comment]
Ok thanks,  of course installing using conda requires that you have conda installed, but that requires conda-env. So this means that the only way to get started with conda is to use miniconda/anaconda. That's ok for me, though you might want to consider removing the pypi package altogether.

**Comment by malev** [comment]
@jolos agree I should remove it but first I need to track whoever has created it :disappointed:
