### ISSUE TITLE
explicit environment with pip requirements? 

### ISSUE THREAD

**Issue by dkoppstein** [conda/conda-env#192]
Hi, I recently found out about the explicit environment file format, created by 

    conda list --explicit > explicit-spec-file.txt

However, AFAIK it seems that this doesn't support pip dependencies supported by the old environment.yml format. Is there a way to put pip dependencies into the new explicit file format?

**Comment by malev** [comment]
@dkoppstein this looks like a question for the [conda](https://github.com/conda/conda) team
