### ISSUE TITLE
How do I install Python3 using Python2 Miniconda?

### ISSUE THREAD

**Issue by piltu007** [conda/conda-env#193]
I have Python2 Miniconda package manager installed in my computer. Can I install Python3 using this package manager? And can I run both Python2 and Python3 side by side?
Thanks.

**Comment by msarahan** [comment]
Yes.

conda create -n <your env name> python=3.4 <any other packages>

or 

conda create -n <your env name> python=3.5 <any other packages>

you need to activate this environment before you can use the other python version.

**Comment by piltu007** [comment]
Thanks @msarahan
