### ISSUE TITLE
Missing consistent way to get the full path of active env (on Windows and Unix)

### ISSUE THREAD

**Issue by tadeu** [conda/conda-env#197]
Since merge #60 the environment variable `CONDA_ENV_PATH` is not defined by `activate` anymore. Is this an intended change or is this a bug?

Some user scripts rely on this variable and it still exists in Linux.

I'll be happy to send a PR if you consider this a bug.

**Comment by tadeu** [comment]
@msarahan and @kalefranz, what is the status of `CONDA_ENV_PATH` and `CONDA_DEFAULT_ENV` on Windows and Unix?

Is there documentation for these variables?

Thanks!

**Comment by msarahan** [comment]
No docs that I know of yet. Please excuse capitalization here. On my phone.

Conda_default_env should be the full path of the active env.  I don't know when conda_env_PATH changed, but I don't think there is intent to bring it back.

There was discussion about changing conda_default_env to conda_active_env at https://github.com/conda/conda/pull/1727 - ultimately it was decided to not change it.

If you mean conda_envs_PATH (manually setting where envs are stored and found, then its absence is/was a bug. I think it works now, and I'm making sure #1727 keeps it working.

**Comment by tadeu** [comment]
Ok, thanks for the quick explanation. :)

(I was meaning about `CONDA_ENV_PATH`, without the `S`)

In this case, since `CONDA_DEFAULT_ENV` is the "official" one, it's ok in Windows, but it seems there are inconsistencies in Unix:

- `CONDA_ENV_PATH` still exists, and is a full path (this should be removed)
- `CONDA_DEFAULT_ENV` may or may not be a full path (if passed something with slashes, it's a full path, otherwise it's just the env name)

**Comment by msarahan** [comment]
Thanks, I'll try to iron out those inconsistencies as part of #1727 - the goal there is really to unify the activation/deactivation process across platforms.

**Comment by kalefranz** [comment]
For the record, I prefer `CONDA_ENV_PATH` over `CONDA_ENVS_PATH` since the variable should be holding a path to a single env. If we're going to change the name of this important environment variable, let's get it right now so that we don't have to change it again in the future.

Also, we should make a separate task/PR to support the old env var for a while with a strongly-worded deprecation warning.

**Comment by msarahan** [comment]
No, you're getting mixed up.  

  - ```CONDA_ENV_PATH``` is a variable that has only been present on linux.  It always held the path of the active environment.
  - ```CONDA_ENVS_PATH``` is used on both Windows and Linux, and is a platform-native list of paths where Conda should look for environments when a name is provided for activation.
  - ```CONDA_DEFAULT_ENV``` is used on both Linux and Windows, and had inconsistent behavior; sometimes showing env name, and sometimes showing env path.

**Comment by tadeu** [comment]
conda/conda#1727 was resolved (good job there!), but it still doesn't touch this issue here, right?

**Comment by msarahan** [comment]
It didn't remove CONDA_ENV_PATH, unfortunately.  Thanks for reminding us of this issue.  I'm going to move it to conda, now that the activate scripts live there (in master, anyway)

**Comment by msarahan** [comment]
Issue moved to [conda/conda #2312](https://github.com/conda/conda/issues/2312) via [**ZenHub.io**](https://www.zenhub.io/)
