### ISSUE TITLE
endlocal statement in activate.bat prevents environment variables being propogates

### ISSUE THREAD

**Issue by stephenakearns** [conda/conda-env#218]
_From @gillins on December 15, 2015 3:3_

Just testing the latest gdal build. There is a gdal-activate.bat that gets properly called to set %GDAL_DATA% but this does not get returned to the user's environment. I think this is due to the endlocal statement preventing set variables getting returned to the caller.

This is easy to test by trying to activate an environment with gdal in it and testing the value to %GDAL_DATA%

_Copied from original issue: Anaconda-Server/support#4_

**Comment by stephenakearns** [comment]
_From @srossross on December 18, 2015 17:20_

@csoja when you have a moment can you make an update on this issue?

**Comment by stephenakearns** [comment]
Hi @gillins - to clarify, you've created an environment with gdal installed and then when you go to conda env source activate you get this error condition where the env variable isn't being set?  cc: @groutr

**Comment by stephenakearns** [comment]
_From @gillins on January 1, 2016 4:30_

Correct.

I can also confirm that putting an endlocal statement in gdal-activate.bat didn't seem to help.

**Comment by gillins** [comment]
Any progress with this? Is a serious problem for advanced GDAL users on Windows...

**Comment by msarahan** [comment]
Please see https://github.com/conda/conda-env/pull/219

As a stopgap, you can replace your activate.bat and deactivate.bat with the modified files in that PR.

Ping @groutr @kalefranz

**Comment by gillins** [comment]
Having to patch installed files isn't a great introduction to Conda for new users who need GDAL. Surely something better can be done here to have it work on a clean install even if there are tweaks to the details later?

**Comment by msarahan** [comment]
I agree. Ping @kalefranz - can we have a conda environment release soon? We need to remove the activate scripts from it, since they live in conda now.  I will submit a PR in a bit.

I wrote a test case specifically for this, so I'm pretty sure it will work after PR 1727.

**Comment by gillins** [comment]
I see #219 has been closed. The current version of activate.bat doesn't seem to allow anything other than PATH and PROMPT to be saved. Has there been a change of plan on how to resolve this?

**Comment by msarahan** [comment]
Conda PR 1727 has been merged and will be in the coming conda 4.1 release.  The test for this behavior is at https://github.com/conda/conda/blob/master/tests/test_activate.py#L712

If you see any deficiency in that test, please let us know how to improve it.

**Comment by msarahan** [comment]
Closing.  This is fixed in activate scripts that now live in conda, not conda env.
