### ISSUE TITLE
Integrate conda-env with conda-build and cas-installer

### ISSUE THREAD

**Issue by srossross** [conda/conda-env#23]
It would be great to define a recipe with a an environment file that specifies the dependencies.

For example, if I had the directory structure:
```
conda.recipe/
  meta.yaml
  environment.yaml
```

Then I would be able to do `conda env create conda.recipe` for development. Or I can do `conda build conda.recipe` and the resulting package would have all of the correct conda deps + the extra environment instructions.

I would also like to be able to package the environment into a CAS installer.

**Comment by malev** [comment]
@srossross if  you already have the environment.yaml then why don't you just run:
`conda env create -f conda.recipe/environment.yml` ?
Or the magic will happend when you run `conda build conda.recipe` ?

**Comment by malev** [comment]
I feel like we could have something like:
`conda env create -n my-env conda.recipes/requirements.txt`
That is actually pretty easy to do

**Comment by malev** [comment]
Not sure what's going on here. Closing
