### ISSUE TITLE
conda env create issue

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-env#232]
_From @olivier65 on March 11, 2016 14:46_

The command "conda env create -f .\requirements.yml" yielded this error:

Traceback (most recent call last):
  File "C:\Python\Miniconda\2\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Python\Miniconda\2\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\Python\Miniconda\2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Python\Miniconda\2\lib\site-packages\conda_env\cli\main_create.py", line 100, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "C:\Python\Miniconda\2\lib\site-packages\conda_env\installers\pip.py", line 8, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

The output of "conda info" is:

platform : win-64
        conda version : 4.0.4
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Python\Miniconda\2  (writable)
  default environment : C:\Python\Miniconda\2
     envs directories : C:\Python\Miniconda\2\envs
        package cache : C:\Python\Miniconda\2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

The requirements.yml file (which GitHub refuses to attach, even after I rename it to *.txt) is:

name: venv.conda
dependencies:
    - cssselect==0.9.1
    - six==1.3.0
    - mock==1.0.1
    - requests==2.4.1
    - numpy==1.6.2
    - pip:
        - Django==1.6.1
        - South==0.8.4
        - django-registration==1.0
        - djangorestframework==2.3.10
        - lxml==3.2.5
        - model-mommy==1.2
        - psycopg2==2.5.1
        - python-dateutil==2.2
        - wsgiref==0.1.2
        - django-filter==0.7
        - pyephem==3.7.5.2
        - pytz2==2014.10

_Copied from original issue: conda/conda#2243_

**Comment by alanhdu** [comment]
This was closed by https://github.com/conda/conda/pull/2264.
