### ISSUE TITLE
Feature request: conda-env should be able to create env outside default path

### ISSUE THREAD

**Issue by dan-vine** [conda/conda-env#236]
With conda create I can use --prefix to specify installation path. I would like to have the same ability for conda-env. 

Reason is: we are planing to use conda-env in an CI setup where we want to create a custom environment for every build. It will be much easier to manage this if the env lies together with the project instead of all envs in anacondas install directory.

**Comment by mshirley** [comment]
+1

I would also like to have the ability to specify a installation path using an environment.yml.

Perhaps we can add a field in environment.yml called "path: relative-path/env"

**Comment by jerowe** [comment]
+1

I support users on a multiuser hpc cluster, and we always use conda create -p, because users don't have access to the main anaconda.

**Comment by nicoddemus** [comment]
We have the same requirement, and we set `CONDA_ENVS_PATH` in our CI scripts:

```
export CONDA_ENVS_PATH=$WORKSPACE/.envs
cd $WORKSPACE/project
conda env create
source activate project-env
py.test src
```

This makes `conda env` create the environment directories in `$WORKSPACE/.envs`.

Posting this just to share the solution we now for those interested, I don't mean to imply that `conda env` should not have a `--prefix` option as well. :grin:

**Comment by msarahan** [comment]
I agree with this request, but we currently do not have the time to implement this.  I welcome PRs, and will do my best to review them quickly.
