### ISSUE TITLE
Allow providing an ad-hoc environment on the command-line again

### ISSUE THREAD

**Issue by filmor** [conda/conda-env#238]
To test packages it's very useful to quickly whip up an environment like it used to work:

    conda create -n py34_test python=3.4 some_package

I'd like this functionality back :)

**Comment by msarahan** [comment]
This should work.  I use this exact syntax often.  Please post any errors you're seeing.

**Comment by filmor** [comment]
I'm sorry, apparently I messed something up in my last tries ...
