### ISSUE TITLE
conda env create not reading valid YAML

### ISSUE THREAD

**Issue by jlafon** [conda/conda-env#247]
Hi there, I've encountered an issue where a generated environment file containing valid YAML is not recognized when lists are [inlined](https://en.wikipedia.org/wiki/YAML#Lists). I had assumed that the environment.yml file could contain valid YAML, but I couldn't find any details in the documentation about it.

Example:

```bash
deploy@7b4e3fc52855:~$ cat environment.yml 
dependencies:
- python=2.7
- pip: [invoke==0.13.0, requests]
name: user_env

deploy@7b4e3fc52855:~$ conda env create --json
Error: Invalid selector in environment.yml line 3:
- pip: [invoke==0.13.0, requests]
```

**Comment by Korijn** [comment]
It parses the inlined lists as if they are preprocessing selectors, just like conda build does. @ivoflipse this looks like a valid use case for parsing preprocessing selectors only when they are in a comment.

**Comment by Korijn** [comment]
I'll put up a PR with the fix tomorrow morning, but there will be discussion, since there are people who depend on the behaviour I'll have to disable.

**Comment by Korijn** [comment]
See here for the preprocessing selectors:

http://conda.pydata.org/docs/building/meta-yaml.html#preprocessing-selectors

For historical reasons that I am unaware of, they are also parsed when outside of a comment. I ported this functionality over to conda-env in #213 (see the PR for more details) and some discussion was had on this topic there as well.

I suppose your bug report is a good reason to only parse them when inside a comment. Thoughts, @kalefranz?

**Comment by Korijn** [comment]
Mentioned discussion on the `#` can be found here: https://github.com/conda/conda-env/pull/213#discussion_r49743104

**Comment by jlafon** [comment]
@Korijn thanks for the quick reply. If anyone else comes across this, you can use the [default_flow_style](http://pyyaml.org/wiki/PyYAMLDocumentation#Dictionarieswithoutnestedcollectionsarenotdumpedcorrectly) argument to safe_dump in PyYAML to force the block style.

**Comment by kalefranz** [comment]
I've been in touch with @Korijn, and selector functionality will be removed from environment.yml as of conda-env 2.5.1.  I'm guessing inline lists will work out-of-the-box now.

I'll be working with @Korijn to figure out alternate implementation possibilities for the capabilities selectors provided.
