### ISSUE TITLE
As of conda 4.1, conda env remove fails with AttributeError: module 'conda.plan' has no attribute 'PREFIX'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-env#248]
@ronert reports https://github.com/conda/conda/issues/2679:

I tried this on three separate machines with conda 4.1.0. Every machine fails with `AttributeError: module 'conda.plan' has no attribute 'PREFIX'` when running `conda env remove -n environment_name` or `conda env remove -p environment_path`. This also happens on my Travis environment now causing my builds to fail. Any ideas?

**Comment by kalefranz** [comment]
A current alternate solution is

    conda remove -n environment_name --all

**Comment by Korijn** [comment]
I can't provide details (on my phone) but this feature of conda env has never worked for me since I became a user 6 months ago, and neither has `conda env create --force`. So, IMHO, I don't think this is a regression type of bug.

**Comment by kalefranz** [comment]
Fixed with #251.
