### ISSUE TITLE
No longer able to override file's name using --name command line argument

### ISSUE THREAD

**Issue by joshowen** [conda/conda-env#254]
Previously we could override the name from an environment file using `--name` in the CLI, but this is no longer respected after the latest release.  This was very useful for heroku buildpacks.

**Comment by dharhas** [comment]
bump. I'm seeing this too. The -n/--name is no longer doing anything.

**Comment by nehalecky** [comment]
bump, same issue. Any workarounds in the interim?

**Comment by nehalecky** [comment]
FWIW, I can get around this by:

```bash
conda create --yes --quiet --name=my-env python=3.5.1
conda update --name=my-env --quiet --yes --all
conda env update  --quiet --name=my-env --file=dependencies.yml
```

**Comment by jseabold** [comment]
What version of conda are you using for this workaround? What version of conda created the environment.yml file?

**Comment by nehalecky** [comment]
@jseabold, the `environment.yml` isn't create by conda, it's crafted by hand. :)

Here's what it looks like!
```
name: coral
dependencies:
# core coral dependencies (must be installed)
  - python>=3.5
  - pip
  - pyyaml
  - pandas
  - numexpr
  - coverage
  - pytest
  - pytest-cov
  - pip:
    # core dependencies
    - findspark
    - bumpversion
    - invoke==0.12.2
    # analytics dependencies
    - coveralls
```


Version info, below:

```
❯ conda info          
Current conda install:

             platform : osx-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.5
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /Users/nehalecky/miniconda3  (writable)
  default environment : /Users/nehalecky/miniconda3
     envs directories : /Users/nehalecky/miniconda3/envs
        package cache : /Users/nehalecky/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/nehalecky/.condarc
         offline mode : False
    is foreign system : False
```

HTH, let me know if you need any other info! Thanks!

**Comment by jseabold** [comment]
`conda env create -n name` ignores name. `conda create -n name` does not ignore name but runs into a parsing error in the `environment.yml` around the name key. I'm not sure I understand the connection between these two things. Would be great if someone could test if #244 introduced this. I don't have a dev setup for doing bisects for conda env.

**Comment by jseabold** [comment]
Ah, I guess it couldn't have introduced this because it's not released yet.

**Comment by jseabold** [comment]
Working off #261. This line in `main_create.py` overwrites the user given name because we're not also specifying a prefix, apparently.

```
        # FIXME conda code currently requires args to have a name or prefix
        if args.prefix is None:
            args.name = env.name
```

**Comment by nehalecky** [comment]
Awsome, is there a unit test to review so I can ensure that I have proper syntax for overriding name via cl arg?

**Comment by jseabold** [comment]
#262 has a smoke test only.

**Comment by jerowe** [comment]
Hi @jseabold, I only just got a chance to look at this. Thanks for fixing it, and sorry about the broken functionality!
