### ISSUE TITLE
Error with conda-env 2.5.1?

### ISSUE THREAD

**Issue by ndclt** [conda/conda-env#256]
After a conda update from conda 4.0.9 to 4.1.3, conda-env has been update from 2.3.2-> 2.5.1.
When I activate a virtual env with 
`activate test_conda_env `
I get an error which I didn't get with conda env 2.3.2.

    prepending D:\\Appl_perso\\Anaconda64\\envs\\test_conda_env and
    D:\\Appl_perso\\Anaconda64\\envs\\test_conda_env\\Library\\mingw-w64\\bin and
    D:\\Appl_perso\\Anaconda64\\envs\\test_conda_env\\Library\\usr\\bin and
    D:\\Appl_perso\\Anaconda64\\envs\\test_conda_env\\Library\\bin and 
    D:\\Appl_perso\\Anaconda64\\envs\\test_conda_env\\Scripts to PATH

Is this a real error or a new feature?

My Conda info:

    platform : win-64
    conda version : 4.1.3
    conda-env version : 2.5.1
    conda-build version : 1.20.0
    python version : 3.5.1.final.0
    requests version : 2.9.1
    root environment : D:\Appl_perso\Anaconda64  (writable)
    default environment : D:\Appl_perso\Anaconda64\envs\test_conda_env
    envs directories : D:\Appl_perso\Anaconda64\envs
    package cache : D:\Appl_perso\Anaconda64\pkgs
    channel URLs : https://repo.continuum.io/pkgs/free/win-64/
               https://repo.continuum.io/pkgs/free/noarch/
               https://repo.continuum.io/pkgs/pro/win-64/
               https://repo.continuum.io/pkgs/pro/noarch/
               https://conda.anaconda.org/conda-forge/win-64/
               https://conda.anaconda.org/conda-forge/noarch/
               https://conda.binstar.org/OpenMDAO/win-64/
               https://conda.binstar.org/OpenMDAO/noarch/
    config file : C:\Users\my_user\.condarc
    offline mode : False
    is foreign system : False

**Comment by Korijn** [comment]
That is just an info message. Do you experience any other problems?

**Comment by ndclt** [comment]
Thanks for the answer.
No any other problems,the env works like usual but the message is managed by [https://github.com/xonsh/xonsh](xonsh) as an error.
