### ISSUE TITLE
Check for `environment.yml` file in multiple locations

### ISSUE THREAD

**Issue by tswicegood** [conda/conda-env#38]
Currently, if `--file` is not specified `conda env` commands assume that you meant the `environment.yml` file located in the current directory.  Change it to look in the following locations:

* `./conda.recipe/environment.ya?ml`
* `./environment.ya?ml`

**Comment by bkreider** [comment]
Please take a look at #50.  I don't think --file should be used in create or export.  Let a user use normal unix semantics to specify an optional input or output file and use stdin/stdout by default.

**Comment by tswicegood** [comment]
@bkreider I'll respond to the stdin behavior in #50.  Regarding this issue, it's related to what this looks for by default when `--file` is not used.

**Comment by malev** [comment]
Not sure if we need this anymore.
