### ISSUE TITLE
Add Description field to environment

### ISSUE THREAD

**Issue by srossross** [conda/conda-env#43]
It would be great to be able to add `description` and/or `README` fields to the environment file. This would be very useful on binstar as well as `conda-env list` e.g.
```sh
conda-env list
# conda environments:
#
_build                   ~/anaconda/envs/_build  | The conda build environment (used internally by conda-build)
asdf                     ~/anaconda/envs/asdf    | A test environment I have created

```

**Comment by tswicegood** [comment]
I like this idea, but I think it's best suited toward after a merge with `conda`.  Right now it would require either PRs to both repos or adding new meta data into the environment that's only present in certain situations.  That would essentially fork what an environment is.

**Comment by srossross** [comment]
That makes sense

**Comment by malev** [comment]
I'll mark this as `wontfix` and close for now
