### ISSUE TITLE
Automatically activate conda environment when entering a folder

### ISSUE THREAD

**Issue by sotte** [conda/conda-env#48]
Hey,

I used [virtualenv_auto_activate.sh](https://gist.github.com/search?q=virtualenv-auto-activate.sh) to automatically activate virtualenvs when entering a folder that contained a ".venv" folder (which is how I store virtualenvs).

I wrote a similar script for conda:
https://gist.github.com/sotte/8fb92dff17264c7a2a85

Maybe you guys are interested in a fleshed out version of this!?

**Comment by sotte** [comment]
I turned my little script into a proper github repo:
https://github.com/sotte/conda_auto_activate

I'll close this issue.

**Comment by tswicegood** [comment]
Nice work @sotte!  Sorry I missed this ticket when it first came in.

**Comment by sotte** [comment]
No problem, just keep up the great work with conda! :)
