### ISSUE TITLE
basename: illegal option -- b

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-env#49]
I am getting this error every time I source activate or deactivate

```
basename: illegal option -- b
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
```

The activation and deactivation seem to work correctly.

**Comment by tswicegood** [comment]
@asmeurer are you still seeing this?

**Comment by asmeurer** [comment]
Nope.

**Comment by tswicegood** [comment]
Awesome! :tada:
