### ISSUE TITLE
make "conda env create" match "conda create"

### ISSUE THREAD

**Issue by gdementen** [conda/conda-env#70]
It is kinda surprising that you can do everything related to environments using `conda env ...`, except create them, yet you have a create command... So I think it should mirror what is possible using "conda create"

I think `conda create` should even be deprecated but that will probably be a tough sell ;-).

**Comment by ccordoba12** [comment]
Yes, I also agree with this change. It's counterintuitive not being able to use `conda env create` to create an environment as it's done with `conda create`

**Comment by malev** [comment]
Don't think this is going to happen, sorry.
