### ISSUE TITLE
Add support for selectors in dependencies

### ISSUE THREAD

**Issue by tswicegood** [conda/conda-env#74]
Currently, dependencies are simple string specification.  Some packages are only required for certain operating systems, versions of Python, and so on.  conda-build solves this problem with [selectors][1], however this presents several limitations:

* Not parseable as strict YAML
* Potential name collision when loading without a pre-processing step (problem presented to other users)

## Solution
Translate simple "some_pkg" specifications into an object and allow dependencies to be expressed with the simple syntax ("some_pkg =1.0"), or with the complete object that specify name, version, and a selector that can be used to determine the same information denoted in conda-build.

[1]: http://conda.pydata.org/docs/build.html#preprocessing-selectors

**Comment by malev** [comment]
Thinking on having jinja templates to solve this

**Comment by nicoddemus** [comment]
@tswicegood please checkout #213

**Comment by tswicegood** [comment]
@nicoddemus I'm no longer involved in this project. Maybe @malev or @ilanschnell could review it.

**Comment by nicoddemus** [comment]
No problem, just wanted to ping you in case you were interested. :smile:
