### ISSUE TITLE
conda env update can result in conda.plan.nothing_to_do(actions) being True when there are actually pip packages to install

### ISSUE THREAD

**Issue by amfarrell** [conda/conda-env#81]
To reproduce:
```
wget https://raw.githubusercontent.com/OpenSourcePolicyCenter/webapp/0e903da4415c889e4779c8e443c1ace87286b630/environment.yml?token=AAHjt6Ph7DQpMMlSQk6QSEHoji1NP7Fyks5VX3zSwA%3D%3D
mv environment.yml aei_environment_0.yml
conda env create --file aei_environment_0.yml
wget https://raw.githubusercontent.com/OpenSourcePolicyCenter/webapp/1a9a0592d81f50755571ef49390ac95fa0f85be3/environment.yml?token=AAHjtz44wpwCPY7HOon8cUy4bIvhOipkks5VX30SwA%3D%3D
mv environment.yml aei_environment_1.yml
conda env update --file aei_environment_1.yml
```

I added djrill to my environment.yml (https://github.com/OpenSourcePolicyCenter/webapp/blob/mailchimp/environment.yml), activated an environment named heroku_aei, and ran `conda env update --file environment.yml`. 
I saw the response
   
   Fetching package metadata: ....................
   Solving package specifications: .# TODO handle more gracefully

This also happens when I run `conda env update --file environment.yml --name heroku_aei`.

https://github.com/conda/conda-env/blob/develop/conda_env/installers/conda.py#L16 is where this occurs. I can confirm that before running the command neither `conda list | grep djrill` nor `pip freeze | grep djrill` show that package to be installed. Installing the package directly with `pip install djrill` works fine. Running `conda env update --file environment.yml` after installing djrill results in the same message.

**Comment by tswicegood** [comment]
Yup -- that'd do it. The original create code requires that something get installed and update was just a copy-n-paste of that.  Any interest in taking a stab at handling the no-action case more gracefully?

**Comment by amfarrell** [comment]
Is it supposed to also do that if there are pip packages to install but no conda packages to install?

**Comment by amfarrell** [comment]
I think that the poor handling of the no-action case is actually a separate issue. The problem here seems to be that it falsely thinks that this is the no-action case.

**Comment by amfarrell** [comment]
For a more minimal environment.yml, see 
https://github.com/amfarrell/react-tutorial/blob/64f98941c8eafdf7ee12ad125addb86c8c5702fe/environment.yml
and then
https://github.com/amfarrell/react-tutorial/blob/680f51f73da70b7ae1768aa9ea61b125194135e2/environment.yml

**Comment by malev** [comment]
Is this somehow related to #89 ?

**Comment by amfarrell** [comment]
yes, this is the same bug as #89

**Comment by amfarrell** [comment]
The message when there is genuinely nothing to install happens to be less-than-clear, but that is a different, less impactful problem.

**Comment by Locky1138** [comment]
+1 Also dealing with this issue

I'm trying to use conda env to deploy the environment for an application, and adding anything that requires pip breaks the deployment script.

**Comment by joshowen** [comment]
Is there an ETA on this being fixed?  Trying to decide if we can use conda in our environment, which will still rely on pip working.

**Comment by malev** [comment]
I'm on vacations now, but I'm guessing sometime next week

**Comment by malev** [comment]
@joshowen, next week hopefully

**Comment by Locky1138** [comment]
@malev thanks for the update, i'll be happy to run some testing to confirm the fix once its done.
