### ISSUE TITLE
Install newly added pip packages on conda env update

### ISSUE THREAD

**Issue by koverholt** [conda/conda-env#89]
If I `conda env update`, then any conda packages that were added to the environment.yml file will be installed, but any pip packages that were added will not be installed.

Is is possible that the `conda env update` command could also check for added pip packages and install them? I use conda env to deploy environments for projects, and this functionality would ensure that a `conda env update` would get the latest conda and pip dependencies that were added to a project.

**Comment by chdoig** [comment]
+1 This just happened to me today.

**Comment by amfarrell** [comment]
This is the same issue as #81

**Comment by malev** [comment]
Will start working on this soon

**Comment by malev** [comment]
So far, the problem is related to this abrupt `sys.exit(1)`
https://github.com/conda/conda-env/blob/develop/conda_env/installers/conda.py#L15-L17

**Comment by koverholt** [comment]
Nice! Verified that this is working in conda-env 2.4.1.
