### ISSUE TITLE
Why use platform specific packages for conda-env?

### ISSUE THREAD

**Issue by campos-ddc** [conda/conda-env#96]
The current recipe and `setup.py` create different packages for windows/unix:

```yaml
  always_include_files:
    - bin/activate              [unix]
    - Scripts/activate.bat      [win]
    - bin/deactivate            [unix]
    - Scripts/deactivate.bat    [win]
```

```python
if sys.platform == 'win32':
    scripts = [
        'bin\\activate.bat',
        'bin\\deactivate.bat',
    ]
else:
    scripts = [
        'bin/activate',
        'bin/deactivate',
    ]
```

Is there a reason for this, other than distributing 2 less files? Maybe some platform specific dependency I don't know about?

If there isn't any other motive, I think that we should distribute a single 'noarch' package, instead of having to create two different ones.

Thoughts?

**Comment by malev** [comment]
Maybe @ilanschnell can help with this

**Comment by ilanschnell** [comment]
Apart from this difference, there are other differences in the conda-env packages for different systems and Python versions.  Since conda-env is a core dependency of conda, it would not be wise to build noarch packages for conda-env.

**Comment by campos-ddc** [comment]
Well, I guess you have your reasons.

Feel free to close this if you wish.
